import type { Metadata } from 'next';

// Shared Open Graph image (generated by src/app/opengraph-image.tsx, served at /opengraph-image).
// A page that sets its own `openGraph` object replaces the one inherited from the root layout,
// which drops the file-convention image — so re-attach it here to keep every share card branded.
export const OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'RokaMaybe — Your Arranged Marriage Tracker',
} as const;

/** Build a page-specific Open Graph block that keeps the shared brand image. */
export function pageOpenGraph(
  title: string,
  description: string,
  type: 'website' | 'article' = 'website',
): Metadata['openGraph'] {
  return { title, description, type, images: [OG_IMAGE] };
}
