import type { Metadata } from 'next';

/** Canonical base URL for the site — used in sitemap.ts, robots.ts, and metadata. */
export const SITE_URL = 'https://rokamaybe.com';

// Shared Open Graph image (generated by src/app/opengraph-image.tsx, served at /opengraph-image).
// A page that sets its own `openGraph` object replaces the one inherited from the root layout,
// which drops the file-convention image — so re-attach it here to keep every share card branded.
export const OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'RokaMaybe — Your Arranged Marriage Tracker',
} as const;

/** Build a page-specific Open Graph block that keeps the shared brand image. */
export function pageOpenGraph(
  title: string,
  description: string,
  type: 'website' | 'article' = 'website',
): Metadata['openGraph'] {
  return { title, description, type, images: [OG_IMAGE] };
}

/**
 * Open Graph for an article, with the dates and byline that `type: 'article'`
 * implies.
 *
 * `pageOpenGraph(..., 'article')` emits `og:type=article` and nothing else, so
 * blog posts declared themselves articles while omitting
 * `article:published_time` and `article:author` entirely — the two properties
 * every reader of that type looks for. Anything setting `type: 'article'`
 * should use this instead.
 */
export function articleOpenGraph(
  title: string,
  description: string,
  article: {
    /** ISO date the post was published (YYYY-MM-DD is fine). */
    publishedTime: string;
    /** ISO date of the last meaningful edit, if there has been one. */
    modifiedTime?: string;
    authors: string[];
    /** The post's category, emitted as article:section. */
    section?: string;
    tags?: string[];
  },
): Metadata['openGraph'] {
  return {
    title,
    description,
    type: 'article',
    images: [OG_IMAGE],
    publishedTime: new Date(article.publishedTime).toISOString(),
    ...(article.modifiedTime
      ? { modifiedTime: new Date(article.modifiedTime).toISOString() }
      : {}),
    authors: article.authors,
    ...(article.section ? { section: article.section } : {}),
    ...(article.tags ? { tags: article.tags } : {}),
  };
}
