import type { Metadata } from 'next';
import LegalLayout from '@/components/LegalLayout';
import { LEGAL } from '@/lib/legal';

export const metadata: Metadata = {
  title: 'Terms & Conditions — RokaMaybe',
  description: 'The terms governing your use of the RokaMaybe service.',
};

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms &amp; Conditions"
      intro={`These Terms & Conditions (“Terms”) govern your use of the ${LEGAL.appName} application and website (the “Service”), operated by ${LEGAL.entity}. By creating an account or using the Service, you agree to these Terms. If you do not agree, do not use the Service.`}
    >
      <h2>1. Eligibility</h2>
      <p>
        You must be at least 18 years old and legally able to enter into a contract to use the Service. By using it,
        you confirm that you meet these requirements.
      </p>

      <h2>2. Your account</h2>
      <p>
        You are responsible for keeping your login credentials secure and for all activity under your account.
        Notify us immediately of any unauthorised use. The information you provide must be accurate and kept
        up to date.
      </p>

      <h2>3. What the Service does</h2>
      <p>
        {LEGAL.appName} is a private organisational tool that helps you track marriage prospects, record notes and
        meetings, and view informational compatibility and kundli (guna milan) scores. It is a personal companion
        tool — it is <strong>not</strong> a matrimonial matchmaking service, marriage bureau, or broker, and we do
        not introduce, verify, or vouch for any person.
      </p>

      <h2>4. Your content &amp; data about other people</h2>
      <p>
        You may enter information about prospective matches (“Prospect data”), including names, photos, phone
        numbers, and biodata. You represent and warrant that:
      </p>
      <ul>
        <li>You have a lawful basis or the necessary consent to collect, upload, and store that information.</li>
        <li>You will use such information only for your own lawful, personal purpose of evaluating a match.</li>
        <li>You will not upload content that is unlawful, defamatory, or infringes anyone’s rights.</li>
      </ul>
      <p>
        You are solely responsible for the Prospect data you add. You agree to indemnify and hold us harmless from
        any claim arising out of your collection or use of another person’s information through the Service.
      </p>

      <h2>5. Astrology, kundli &amp; compatibility scores — important disclaimer</h2>
      <div className="note">
        Kundli/guna milan scores, compatibility percentages, “warmth”, flags, and any other metrics in the Service
        are generated by automated formulas for your <strong>informational and reference use only</strong>. They are
        <strong> not</strong> astrological, religious, legal, financial, medical, or professional advice, and are
        <strong> not</strong> a prediction or guarantee of compatibility, marriage outcome, or any result. Decisions
        you make about people or relationships are entirely your own.
      </div>

      <h2>6. AI features</h2>
      <p>
        The optional biodata-extraction feature uses third-party AI to read documents/images you upload. AI output
        may be incomplete or inaccurate. Always review and verify extracted information before relying on it.
      </p>

      <h2>7. Acceptable use</h2>
      <ul>
        <li>Do not use the Service for any unlawful purpose or to harass, stalk, or harm anyone.</li>
        <li>Do not attempt to breach security, access other users’ data, or disrupt the Service.</li>
        <li>Do not scrape, resell, or abuse the Service or its automated endpoints.</li>
      </ul>

      <h2>8. Intellectual property</h2>
      <p>
        The Service, including its software, design, and content (excluding your data), is owned by us or our
        licensors and is protected by applicable laws. You retain ownership of the data you submit.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        The Service is provided <strong>“as is” and “as available”</strong>, without warranties of any kind, whether
        express or implied, including fitness for a particular purpose, accuracy, or uninterrupted availability. We
        do not warrant that the Service will be error-free or that scores or extracted data will be accurate.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, we will not be liable for any indirect, incidental, special,
        consequential, or punitive damages, or for any loss arising from decisions you make based on the Service,
        the conduct of any prospect or third party, or any inaccuracy in scores or extracted data. To the extent we
        are found liable, our total aggregate liability shall not exceed the amount you paid us (if any) for the
        Service in the twelve months preceding the claim.
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless {LEGAL.entity} and its operators from any claims, damages, or
        expenses arising from your use of the Service, your content or Prospect data, or your breach of these Terms.
      </p>

      <h2>12. Termination</h2>
      <p>
        You may stop using the Service and request account deletion at any time. We may suspend or terminate access
        if you breach these Terms or use the Service unlawfully.
      </p>

      <h2>13. Governing law &amp; jurisdiction</h2>
      <p>
        These Terms are governed by the laws of {LEGAL.governingLaw}. You agree to the exclusive jurisdiction of the
        courts at {LEGAL.jurisdictionCity}, {LEGAL.governingLaw}, subject to any non-waivable rights you have under
        local law.
      </p>

      <h2>14. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the Service after changes take effect means you
        accept the updated Terms.
      </p>

      <h2>15. Contact</h2>
      <p>
        Questions about these Terms? Email <a href={`mailto:${LEGAL.contactEmail}`}>{LEGAL.contactEmail}</a>.
      </p>
    </LegalLayout>
  );
}
